<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:03AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:01AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 28, 2015 9:00AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)</p>

		<p><strong>Code:</strong> 2003</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(54): PDO->__construct('mysql:host=127....', 'root', 'root')
#1 /var/www/html/v2-master/app/core/controller.php(34): helpers\Database::get()
#2 /var/www/html/v2-master/app/controllers/application.php(9): core\Controller->__construct()
#3 /var/www/html/v2-master/app/core/router.php(80): controllers\Application->__construct(NULL)
#4 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\ap...')
#5 /var/www/html/v2-master/index.php(81): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<p>Error on Jan 27, 2015 16:53PM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/msgdisplay.php on line 19</p><p>Error on Jan 26, 2015 17:32PM - Illegal string offset 'sl_no' in /var/www/html/v2-master/app/views/applications.php on line 24</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:12PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:11PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 23, 2015 12:10PM</p>

		<p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'postman.users' doesn't exist</p>

		<p><strong>Code:</strong> 42S02</p>

		<p><strong>File:</strong> /var/www/html/v2-master/app/helpers/database.php</p>

		<p><strong>Line:</strong> 86</p>

		<h3>Stack trace:</h3>

		<pre>#0 /var/www/html/v2-master/app/helpers/database.php(86): PDOStatement->execute()
#1 /var/www/html/v2-master/app/controllers/welcome.php(23): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 /var/www/html/v2-master/app/core/router.php(85): controllers\Welcome->index()
#3 /var/www/html/v2-master/app/core/router.php(196): core\Router::invokeObject('\controllers\we...')
#4 /var/www/html/v2-master/index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<p>Error on Jan 23, 2015 11:50AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:50AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:49AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 23, 2015 11:47AM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/home.php on line 18</p><p>Error on Jan 22, 2015 16:48PM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/msgdisplay.php on line 19</p><p>Error on Jan 22, 2015 16:48PM - Invalid argument supplied for foreach() in /var/www/html/v2-master/app/views/msgdisplay.php on line 19</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:41AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:32AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:31AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:30AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:30AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:29AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:29AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:28AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 9:28AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:10AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:09AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:09AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(9): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:04AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:04AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:04AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:00AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 7:00AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:51AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:51AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:51AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:51AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:51AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:50AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:50AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:50AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:49AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:49AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:49AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:49AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:49AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 12, 2015 6:47AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)</p>

		<p><strong>Code:</strong> 1045</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(34): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\core\error.php(25): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): core\Error->__construct('No routes found...')
#4 C:\xampp\htdocs\v2-master\app\core\router.php(271): core\Router::invokeObject('\\core\\error@ind...', NULL, 'No routes found...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<p>Error on Jan 11, 2015 17:14PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 17:13PM</p>

		<p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: Columns/Parameters are 1-based</p>

		<p><strong>Code:</strong> HY093</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 82</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(82): PDOStatement->bindValue('0', '')
#1 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(33): helpers\Database->select('SELECT * FROM a...', Array, 2)
#2 C:\xampp\htdocs\v2-master\app\core\router.php(85): controllers\Welcome->index()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#4 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 17:12PM</p>

		<p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: Columns/Parameters are 1-based</p>

		<p><strong>Code:</strong> HY093</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 82</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(82): PDOStatement->bindValue('0', '')
#1 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(33): helpers\Database->select('SELECT COUNT(*)...', Array, 2)
#2 C:\xampp\htdocs\v2-master\app\core\router.php(85): controllers\Welcome->index()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#4 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#5 {main}</pre>

		<hr />
<p>Error on Jan 11, 2015 17:07PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><p>Error on Jan 11, 2015 17:07PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><p>Error on Jan 11, 2015 17:07PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><p>Error on Jan 11, 2015 17:02PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><p>Error on Jan 11, 2015 17:02PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\v2-master\app\helpers\database.php on line 78</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:09PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:09PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:09PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:07PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:07PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:07PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:04PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:03PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:03PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:03PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:02PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:00PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 12:00PM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 11:57AM</p>

		<p><strong>Message:</strong> could not find driver</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(236): core\Router::invokeObject('\\controllers\\we...', Array)
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:41AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:41AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:38AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:36AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:36AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:35AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Jan 11, 2015 7:35AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
</p>

		<p><strong>Code:</strong> 2002</p>

		<p><strong>File:</strong> C:\xampp\htdocs\v2-master\app\helpers\database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 C:\xampp\htdocs\v2-master\app\helpers\database.php(54): PDO->__construct('mysql:host=127....', '', '')
#1 C:\xampp\htdocs\v2-master\app\core\controller.php(33): helpers\Database::get()
#2 C:\xampp\htdocs\v2-master\app\controllers\welcome.php(19): core\Controller->__construct()
#3 C:\xampp\htdocs\v2-master\app\core\router.php(80): controllers\Welcome->__construct(NULL)
#4 C:\xampp\htdocs\v2-master\app\core\router.php(196): core\Router::invokeObject('\\controllers\\we...')
#5 C:\xampp\htdocs\v2-master\index.php(78): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<p>Error on Jan 08, 2015 17:22PM - require(app/templates/mytemplate/header.php): failed to open stream: No such file or directory in C:\xampp\htdocs\v2-master\app\core\view.php on line 42</p><p>Error on Jan 08, 2015 6:53AM - require(app/templates/mytemplate/header.php): failed to open stream: No such file or directory in C:\xampp\htdocs\v2-master\app\core\view.php on line 42</p>
